version: '3.8'
services:
  task-management-nest-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: task-management-nest
      POSTGRES_PASSWORD: password
    volumes:
      - task-management-nest-db-volume:/var/lib/ task-management-nest-db-volume/data
    ports:
      - 5432:5432

volumes:
  task-management-nest-db-volume: